In [1]:
import pandas as pd
import numpy as np
import math
from scipy.stats import poisson

In [69]:
df = pd.read_csv('../assets/liga1920.csv')

liga1920 = df[df['HomeTeam']=='Barcelona']
home1920 = liga1920[liga1920['FTAG']==0]

liga1920 = df[df['AwayTeam']=='Barcelona']
away1920 = liga1920[liga1920['FTHG']==0]


df = pd.read_csv('../assets/liga1819.csv')

liga1819 = df[df['HomeTeam']=='Barcelona']
home1819 = liga1819[liga1819['FTAG']==0]

liga1819 = df[df['AwayTeam']=='Barcelona']
away1819 = liga1819[liga1819['FTHG']==0]


df = pd.read_csv('../assets/liga1718.csv')

liga1718 = df[df['HomeTeam']=='Barcelona']
home1718 = liga1718[liga1718['FTAG']==0]

liga1718 = df[df['AwayTeam']=='Barcelona']
away1718 = liga1718[liga1718['FTHG']==0]


df = pd.read_csv('../assets/liga1617.csv')

liga1617 = df[df['HomeTeam']=='Barcelona']
home1617 = liga1617[liga1617['FTAG']==0]

liga1617 = df[df['AwayTeam']=='Barcelona']
away1617 = liga1617[liga1617['FTHG']==0]


df = pd.read_csv('../assets/liga1516.csv')

liga1516 = df[df['HomeTeam']=='Barcelona']
home1516 = liga1516[liga1516['FTAG']==0]

liga1516 = df[df['AwayTeam']=='Barcelona']
away1516 = liga1516[liga1516['FTHG']==0]


df = pd.read_csv('../assets/liga1415.csv')

liga1415 = df[df['HomeTeam']=='Barcelona']
home1415 = liga1415[liga1415['FTAG']==0]

liga1415 = df[df['AwayTeam']=='Barcelona']
away1415 = liga1415[liga1415['FTHG']==0]


df = pd.read_csv('../assets/liga1314.csv')

liga1314 = df[df['HomeTeam']=='Barcelona']
home1314 = liga1314[liga1314['FTAG']==0]

liga1314 = df[df['AwayTeam']=='Barcelona']
away1314 = liga1314[liga1314['FTHG']==0]


df = pd.read_csv('../assets/liga1213.csv')

liga1213 = df[df['HomeTeam']=='Barcelona']
home1213 = liga1213[liga1213['FTAG']==0]

liga1213 = df[df['AwayTeam']=='Barcelona']
away1213 = liga1213[liga1213['FTHG']==0]


df = pd.read_csv('../assets/liga1112.csv')

liga1112 = df[df['HomeTeam']=='Barcelona']
home1112 = liga1112[liga1112['FTAG']==0]

liga1112 = df[df['AwayTeam']=='Barcelona']
away1112 = liga1112[liga1112['FTHG']==0]


df = pd.read_csv('../assets/liga1011.csv')

liga1011 = df[df['HomeTeam']=='Barcelona']
home1011 = liga1011[liga1011['FTAG']==0]

liga1011 = df[df['AwayTeam']=='Barcelona']
away1011 = liga1011[liga1011['FTHG']==0]


df = pd.read_csv('../assets/liga0910.csv')

liga0910 = df[df['HomeTeam']=='Barcelona']
home0910 = liga0910[liga0910['FTAG']==0]

liga0910 = df[df['AwayTeam']=='Barcelona']
away0910 = liga0910[liga0910['FTHG']==0]



df = pd.read_csv('../assets/liga0809.csv')

liga0809 = df[df['HomeTeam']=='Barcelona']
home0809 = liga0809[liga0809['FTAG']==0]

liga0809 = df[df['AwayTeam']=='Barcelona']
away0809 = liga0809[liga0809['FTHG']==0]

In [3]:
season19 = pd.concat([home1920, away1920])
season18 = pd.concat([home1819, away1819])
season17 = pd.concat([home1718, away1718])
season16 = pd.concat([home1617, away1617])
season15 = pd.concat([home1516, away1516])
season14 = pd.concat([home1415, away1415])
season13 = pd.concat([home1314, away1314])
season12 = pd.concat([home1213, away1213])
season11 = pd.concat([home1112, away1112])
season10 = pd.concat([home1011, away1011])
season09 = pd.concat([home0910, away0910])
season08 = pd.concat([home0809, away0809])

In [4]:
season19 = season19[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']]
season19 = season19.rename(columns={'FTHG':'HomeGoals', 'FTAG':'AwayGoals'})

In [5]:
season18 = season18[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']]
season18 = season18.rename(columns={'FTHG':'HomeGoals', 'FTAG':'AwayGoals'})

In [6]:
print(season19.shape)
print(season18.shape)
print(season17.shape)
print(season16.shape)
print(season15.shape)
print(season14.shape)
print(season13.shape)
print(season12.shape)
print(season11.shape)
print(season10.shape)
print(season09.shape)
print(season08.shape)

(15, 5)
(17, 5)
(19, 64)
(13, 64)
(18, 64)
(23, 67)
(16, 67)
(10, 73)
(19, 70)
(19, 70)
(20, 70)
(15, 70)

In [7]:
win19 = (15 / 38 * 100)
win19 = round(win19, 2)
win19

39.47

## 失点確率分布

In [8]:
# poisson_pred = np.column_stack([[poisson.pmf(i, season19.mean()[j])for i in range(9)]for j in range(2)])

# fig,ax = plt.subplots(figsize=(10,5))

# plt.hist(season19)

In [61]:
df = pd.read_csv('../assets/liga1920.csv')

liga1920home = df[df['HomeTeam']=='Barcelona']
liga1920home = liga1920home[['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']]
liga1920home = liga1920home.rename(columns={'FTHG':'HomeGoals', 'FTAG': 'againstG(H)'})

liga1920away = df[df['AwayTeam']=='Barcelona']
liga1920away = liga1920away[['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']]
liga1920away = liga1920away.rename(columns={'FTHG':'againstG(A)', 'FTAG': 'AwayGoals'})
liga1920home.reset_index(drop=True, inplace=True)
liga1920away.reset_index(drop=True, inplace=True)

In [71]:
liga1920 = pd.concat([liga1920home, liga1920away], axis=1)
liga1920

,HomeTeam,AwayTeam,HomeGoals,againstG(H),HomeTeam,AwayTeam,againstG(A),AwayGoals
0,Barcelona,Betis,5,2,Ath Bilbao,Barcelona,1,0
1,Barcelona,Valencia,5,2,Osasuna,Barcelona,2,2
2,Barcelona,Villarreal,2,1,Granada,Barcelona,2,0
3,Barcelona,Sevilla,4,0,Getafe,Barcelona,0,2
4,Barcelona,Valladolid,5,1,Eibar,Barcelona,0,3
5,Barcelona,Celta,4,1,Levante,Barcelona,3,1
6,Barcelona,Mallorca,5,2,Leganes,Barcelona,1,2
7,Barcelona,Real Madrid,0,0,Ath Madrid,Barcelona,0,1
8,Barcelona,Alaves,4,1,Sociedad,Barcelona,2,2
9,Barcelona,Granada,1,0,Espanol,Barcelona,2,2
10,Barcelona,Levante,2,1,Valencia,Barcelona,2,0
11,Barcelona,Getafe,2,1,Betis,Barcelona,2,3
12,Barcelona,Eibar,5,0,Real Madrid,Barcelona,2,0
13,Barcelona,Sociedad,1,0,Mallorca,Barcelona,0,4
14,Barcelona,Leganes,2,0,Sevilla,Barcelona,0,0
15,Barcelona,Ath Bilbao,1,0,Celta,Barcelona,2,2
16,Barcelona,Ath Madrid,2,2,Villarreal,Barcelona,1,4
17,Barcelona,Espanol,1,0,Valladolid,Barcelona,0,1
18,Barcelona,Osasuna,1,2,Alaves,Barcelona,0,5

SyntaxError: invalid syntax (<ipython-input-67-fc0a9fb5bc83>, line 4)

In [73]:
df = pd.read_csv('../assets/liga1920.csv')
liga1920 = df[df['AwayTeam']=='Barcelona']
liga1920

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,16/08/2019,20:00,Ath Bilbao,Barcelona,1,0,H,0,0,...,1.97,0.75,1.93,2.00,1.91,2.01,2.02,2.03,1.91,1.98
22,SP1,31/08/2019,16:00,Osasuna,Barcelona,2,2,D,1,0,...,1.96,1.00,2.11,1.82,2.09,1.83,2.16,1.85,2.10,1.80
44,SP1,21/09/2019,20:00,Granada,Barcelona,2,0,H,1,0,...,2.25,1.25,1.88,2.05,1.88,2.04,2.01,2.10,1.87,2.01
62,SP1,28/09/2019,15:00,Getafe,Barcelona,0,2,A,0,1,...,1.69,0.25,2.11,1.82,2.12,1.81,2.26,1.85,2.11,1.80
81,SP1,19/10/2019,12:00,Eibar,Barcelona,0,3,A,0,1,...,2.40,1.25,1.86,2.07,1.83,2.09,2.00,2.21,1.85,2.04
110,SP1,02/11/2019,15:00,Levante,Barcelona,3,1,H,0,1,...,3.80,1.75,2.06,1.87,2.04,1.88,2.08,1.98,2.01,1.88
130,SP1,23/11/2019,12:00,Leganes,Barcelona,1,2,A,1,0,...,1.90,0.75,2.07,1.86,2.08,1.84,2.25,1.87,2.10,1.79
148,SP1,01/12/2019,20:00,Ath Madrid,Barcelona,0,1,A,0,0,...,1.71,0.00,2.03,1.90,2.03,1.88,2.14,1.92,2.03,1.85
161,SP1,14/12/2019,15:00,Sociedad,Barcelona,2,2,D,1,1,...,2.54,1.00,1.85,2.08,1.83,2.09,1.98,2.09,1.85,2.01
185,SP1,04/01/2020,20:00,Espanol,Barcelona,2,2,D,1,0,...,2.27,1.50,1.87,2.06,1.86,2.05,2.02,2.09,1.86,2.00
202,SP1,25/01/2020,15:00,Valencia,Barcelona,2,0,H,0,0,...,2.37,0.75,2.03,1.90,2.03,1.89,2.07,1.91,2.00,1.86
229,SP1,09/02/2020,20:00,Betis,Barcelona,2,3,A,2,2,...,2.46,0.50,2.01,1.92,1.99,1.93,2.06,1.95,1.99,1.87
258,SP1,01/03/2020,20:00,Real Madrid,Barcelona,2,0,H,0,0,...,2.33,-0.25,1.91,2.02,1.92,2.00,1.97,2.05,1.90,1.98
276,SP1,13/06/2020,21:00,Mallorca,Barcelona,0,4,A,0,2,...,2.66,1.50,1.90,2.03,1.85,2.07,2.10,2.07,1.94,1.94
292,SP1,19/06/2020,21:00,Sevilla,Barcelona,0,0,D,0,0,...,1.96,0.25,2.08,1.85,2.08,1.85,2.09,1.96,2.05,1.83
312,SP1,27/06/2020,16:00,Celta,Barcelona,2,2,D,0,1,...,2.07,1.25,2.02,1.77,2.11,1.83,2.13,1.88,2.06,1.82
337,SP1,05/07/2020,21:00,Villarreal,Barcelona,1,4,A,1,3,...,2.44,0.75,1.87,2.06,1.88,2.04,1.95,2.06,1.88,2.00
351,SP1,11/07/2020,18:30,Valladolid,Barcelona,0,1,A,0,1,...,2.11,1.50,1.99,1.94,1.99,1.93,2.12,1.99,1.95,1.93
370,SP1,19/07/2020,16:00,Alaves,Barcelona,0,5,A,0,3,...,2.46,1.25,2.05,1.88,2.05,1.86,2.11,1.95,2.01,1.87